### ISSUE TITLE
We should implement training sessions

### ISSUE THREAD

**Issue by Bad-Grandpa** [Bad-Grandpa/ReadWriteExecute#14]
Since our app is made to learn japanese, we should implement any form of training with flashcard. 
My simple idea is:
User picks a lesson that is problematic for him and clicks on train button.
Then new page opens and it shows any card from lesson with word in given language and three options for translation (2 of them incorrect).
When user picks a one of options, view shows next random card. After picking all the answers user can see the score (sum of all correct answers).
@Seblis  Since for now you are the only dev here, you can describe how would you approach this.

**Comment by Seblis** [comment]
Each entry of the lesson list, instead of being a link, should have two seperate buttons - Edit and Learn.

"Learn" button will forward user to the url `/learnjapanese/lesson/<lesson_id>/train`. In the first, simple version it will forward straight into the first question - the question no. will be tracked using url query, eg. first question will be available under `/learnjapanese/lesson/<lesson_id>/train/?question=1`. The user progress will be tracked using django session feature (https://docs.djangoproject.com/en/4.1/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase). After the last question, customer will be forwarded to `/learnjapanese/lesson/<lesson_id>/train/results`, where he can see the score and choose next action - displaying lesson list or starting another attempt with the current one.

Additional notes:
1) Additional false entries will be chosen randomly in corresponding view every time a new question url is called
2) The solution should prevent customer from accessing question by directly typing it. The idea is to create secret token being a hash of the session token and pass it in the context. Also caching will be disabled in order to prevent back button from taking an effect.
3) Described solution should be easily adjustable for future features like saving your result as a user, or choosing difficulty which can be stored eg. in context

**Comment by Seblis** [comment]
Quick update on the progress:

Right now base for all the elements is created.
TODO:
- correct score increment
- displaying result page at the end of the training
- after particular question is loaded once, we need to save random false choices in session in order to prevent changing answers on refresh. I will figure out an elegant way to handle that.
