### ISSUE TITLE
We should decide on user account technology

### ISSUE THREAD

**Issue by Bad-Grandpa** [Bad-Grandpa/ReadWriteExecute#6]
We should make a decision whether we stay with django accounts or should introduce new solution for accounts feature

**Comment by Seblis** [comment]
After consideration I would leave django default user authentication - reason being that users will have limited set of acction that do not affect core functionality of the app. Database entries will be created from external source by running customer python script in django shell.

**Comment by Bad-Grandpa** [comment]
Agreed. This will also help with troubleshooting (most of our cases will probably be already named somewhere) and development speed (many how-to's).

**Comment by Seblis** [comment]
After some rethinking this is about the last moment we can change user account behavior. I decided to override custom User with... nothing. What makes this good practice is the fact that if we decide on additional User info, we only need to modify current user class instead of replacing it completely (or replace with the subclass). Since adding a new field is just a simple migration while switching classes just destroys database, I opted for a subclass that is identical with `django.contrib.auth.models.AbstractUser` (at least for the time being).
